### ISSUE TITLE
Whiteboard

### ISSUE THREAD

**Issue by jjsarton** [wirow-io/wirow-server#12]
Guest may open the whiteboard, even if this disabled! Of course the can it but there is no connection.

**Comment by jjsarton** [comment]
1) Start and enter a meeting room
2) With a second system (or browser) enter the room a guest
2.1) click on the whiteboard button as guest.
      A tab trying to open the whiteboard will be opened on the guest browser.

file wirow.ini

**Comment by jjsarton** [comment]
The white board is worser. I have set the variable public_available to true for my latest test.
1) System A login, start meeting
2) System B login, join meeting
3) on A open witheboard. page  remain waiting for data
4) on B click on the advise popup, the whiteboard is opened and may be modified.

On A no way to see any tings, the APP sent requests, none is answered.

**Comment by adamansky** [comment]
> The white board is worser. I have set the variable public_available to true for my latest test.
> 
>     1. System A login, start meeting
> 
>     2. System B login, join meeting
> 
>     3. on A open witheboard. page  remain waiting for data
> 
>     4. on B click on the advise popup, the whiteboard is opened and may be modified.
> 
> 
> On A no way to see any tings, the APP sent requests, none is answered.

Still cannot reproduce it i various environments. I suspect the network related issues. Will investigate it. Anyway thank you for reporting.

**Comment by jjsarton** [comment]
Apparently I have problems with the TLS connection. On System B all is Okay, I don't see TLS Hello messages.
I may have this on both system if this appears. I had to play on both browsers and got the error on both side,

**Comment by jjsarton** [comment]
After configured the optional dtls certificate, this seems to work better. Closing the tab is always not a good idea. In order to recover the whiteboard. I disconnect the browser and go on the first history mentioning Wirow call it and join the meeting again. If I do this, I call access the whiteboard again.

**Comment by jjsarton** [comment]
I confirm that the behavior is, according to my test, okay.
