### ISSUE TITLE
Having some issues

### ISSUE THREAD

**Issue by DillFrescott** [wirow-io/wirow-server#2]
I love this project! It has so much potential! But I'am having difficulties getting it to work.

I built the docker image and the farthest I got was getting to the login screen. I am just testing it on my computer so i set it to listen on `0.0.0.0:8080` and bound the container ports to the host. I can get to the login screen if i use `-p 8080:8080` in the start command but it won't work if I use `--network host` instead for some odd reason.

At the login screen I am able to put in the admin username and my set password but the page never changes off of the login page for some reason.

Any help would be appreciated! :)

**Comment by adamansky** [comment]
Hi! We have updated documentation concerning using of docker images. Please check this out: https://github.com/wirow-io/wirow-server/blob/master/docker/README.md Hope it will help in resolving your problem.

**Comment by adamansky** [comment]
Also we have fixed some issues when server operates over `http` (not https) or under proxy so think all will be ok. 
Please reopen this ticket if you will have problems.
