### ISSUE TITLE
Segment violation on recording end

### ISSUE THREAD

**Issue by jjsarton** [wirow-io/wirow-server#25]
1) modify the cmakefile.txt and disable recording, rebuild binary.
2) login and start meeting, start recording.
3) stop recording, wirow will crash.

**Comment by adamansky** [comment]
I think you need a full rebuild: `rm -rf ./build/*`  in the case when some global configuration options changed. 
I admin what some changed build options over the previous build can lead to binary file  inconsistency. So closing it since never let this situation happen.

**Comment by jjsarton** [comment]
I have always cleaned the build directory via ninja clean. So all components will be build again. The problem appeared on my old download. I have now a new clone (not modified).

**Comment by jjsarton** [comment]
Okay I will do this, if I want to make a special build.
