### ISSUE TITLE
Ticket issued by wirow

### ISSUE THREAD

**Issue by jjsarton** [wirow-io/wirow-server#26]
1) login and start a meeting
2) join the meeting as guest with another browser
3) leave the meeting (both systems)
4) logout; close the browser

5) open browser and login again
   I get wirow.example.org/ws/ticket?1654010863897. Before the may be an error for initialing the app.
   creating the room tell "unspecified"

If I wait for a long time, wirow may work again.

**Comment by adamansky** [comment]
Is it reliable reproducible? Which browser needs to be closed at step `4.`?

**Comment by jjsarton** [comment]
This seems to be related to issues #12. I think that this may be related to dtls certificate.

**Comment by jjsarton** [comment]
May be considered okay, and closed. If this happens erase the part ?ticket=... and reload the page, there is no problem and the first error sit 40 cm in front of the display.
