### ISSUE TITLE
whiteboard data

### ISSUE THREAD

**Issue by jjsarton** [wirow-io/wirow-server#27]
The whiteboard data are not removed.
1) make sure that no whiteboard data are present
2) login and enter a room
3) open whiteboard and insert some figure
4) leave the whiteboard and the room
5) look after a few minutes for whiteboard entries in the db.

The wirow.ini file contained

```
[whiteboard]
 room_data_ttl_sec = 120
```
I had expected that the entries will be removed after  closing all sessions entities and waiting up to the ttl.

**Comment by jjsarton** [comment]
The problem reside within parsing the wirow.in file.
I had the following content:

```
room_data_ttl_sec = 10
 public_available = false
```
room_data_ttl_sec first sett correctly to 10 and then to room_data_ttl_sec=public_available which result to put 0
According to src/utils/ the file shall be interpreted line ny line!

**Comment by adamansky** [comment]
```
room_data_ttl_sec = 10
-->  public_available = false
```
Try to remove leading whitespace before `public_available` and all will be ok.
Every config `key=value` should be started with non space symbol

**Comment by adamansky** [comment]
Checked room_data_ttl_sec is works as expected. Please reopen this ticket again if you the issue will remain
