### ISSUE TITLE
Wrong behavour if the url contain  parameters.

### ISSUE THREAD

**Issue by jjsarton** [wirow-io/wirow-server#29]
1) launch wirow, start a meeting
2) launch a second browser with the meeting address followed by ?xxx=1234
  +  the login mask is shown so that you can't log in as guest

**Comment by adamansky** [comment]
Hi! Did you try the following URL format: https://192.168.1.37:8888/?xxx=zzz#00e1f2d1-2c1e-4ef1-b2a6-53e914a90590
It works well if query params are before hash part.

According to https://www.rfc-editor.org/rfc/rfc3986#section-3 hash part should be last 
```
URI         = scheme ":" hier-part [ "?" query ] [ "#" fragment ]
```

**Comment by jjsarton** [comment]
Okay this work
